### ISSUE TITLE
Get Status method not work

### ISSUE THREAD

**Issue by deodatus** [dapi-co/dapi-api#13]
**Describe the bug**
`POST https://api.dapi.co/v1/status`
returns HTTP 404 error
```
{
    "success": false,
    "msg": "Endpoint not found"
}
``` 

**To Reproduce**
1. Call `POST https://api.dapi.co/v1/status` (with valid credentials) and send JSON payload like
```
{
	"sync": true,
	"appKey": "[REDACTED]",
	"appSecret": "[REDACTED]",
	"userSecret": "[REDACTED]",
	"jobID": "6867b6db-6077-40c5-81fb-a3e675008b30"
}
```

**Expected behavior**
Must return HTTP 200 response.

**Additional context**
Both sandbox users

**Comment by omar-sobhy** [comment]
Seems like the docs were outdated. We just updated them with the proper URL to use for this endpoint. For querying a job's status, the URL is https://api.dapi.co/v1/job/status, and to create a new beneficiary (#15), the URL is https://api.dapi.co/v1/payment/beneficiaries/create.
